<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tingkat Pendidikan_TingkatPendidikannama</name>
   <tag></tag>
   <elementGuidId>89462352-03fd-4bc1-b5c7-ab54377aa401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tingkatpendidikan-nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tingkatpendidikan-nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c71f16ad-37be-4167-924f-32aee4a3181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2b7af83-c611-4617-b100-d95f2154c1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tingkatpendidikan-nama</value>
      <webElementGuid>35d520df-4ca4-4366-8143-3c7c99f4f57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>af8fc0da-02e7-46b7-ae42-1ce352c3f19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TingkatPendidikan[nama]</value>
      <webElementGuid>0fdec9e4-84bf-450b-bbb4-91eac2521a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SD</value>
      <webElementGuid>46291fc5-0fd1-4a8e-820a-e8e4f30957ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>09661b8a-81f9-482c-9009-6505d55d9755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eeef50b6-914e-494f-9c1c-20698629f264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tingkatpendidikan-nama&quot;)</value>
      <webElementGuid>3ae60519-86bb-4552-a941-be2a09c1f5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tingkatpendidikan-nama']</value>
      <webElementGuid>274bcbf6-504b-4706-86c7-4e2074d2005c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/input</value>
      <webElementGuid>97daf9ef-342c-4116-8c4b-7b80db297929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c92b7db4-68cd-4dac-b758-697904391eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tingkatpendidikan-nama' and @name = 'TingkatPendidikan[nama]']</value>
      <webElementGuid>2b8af0c7-e280-4abf-b662-d4a6797ff0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
