<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tingkat Pendidikan_TingkatPendidikannama</name>
   <tag></tag>
   <elementGuidId>130c4c31-0b08-4ef0-9bf3-442e49a9d6d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tingkatpendidikan-nama</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tingkatpendidikan-nama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a703b512-dff2-4f23-8601-966158f70971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be793100-1a88-4bcc-ab1d-e9494601965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tingkatpendidikan-nama</value>
      <webElementGuid>839147f1-e607-428a-a405-3580723da03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a86e8946-214d-4f85-bb2b-c23bea5db1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TingkatPendidikan[nama]</value>
      <webElementGuid>c6583b1f-c302-4735-bfd1-7a0b13bc23c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>a54e313c-df4d-4816-bf29-c273cbe195cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>af2712b5-0107-434f-9e13-92b0daebc94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tingkatpendidikan-nama&quot;)</value>
      <webElementGuid>9a0b3983-1594-4359-b76a-c730cdf2011f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tingkatpendidikan-nama']</value>
      <webElementGuid>fc5925b1-b2f5-4e72-b4af-c2a73fc35fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='w0']/div/input</value>
      <webElementGuid>4e5be284-056a-4bed-8717-0bec7aeb2770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>51409fb2-69e7-4a65-b3e9-3110165c7a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tingkatpendidikan-nama' and @name = 'TingkatPendidikan[nama]']</value>
      <webElementGuid>e63bf73b-0d34-471d-a462-78840fc0e6c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
